// Code generated by protoc-gen-go-binary. DO NOT EDIT.
// source: e2e.proto

package e2e

// MarshalBinary implements encoding.BinaryMarshaler
func (msg *Basic) MarshalBinary() ([]byte, error) {
	return msg.Marshal()
}

// UnmarshalBinary implements encoding.BinaryUnmarshaler
func (msg *Basic) UnmarshalBinary(b []byte) error {
	return msg.Unmarshal(b)
}
